subject_length = 50
line_length = 72
subject_capitalized = false
subject_not_punctuated = true
imperative_subject = true
no_fixup = true
no_wip = true
style = "conventional"
allowed_types = [
  "fix",
  "feat",
  "docs",
  "style",
  "refactor",
  "perf",
  "test",
  "build",
  "ci",
]
merge_commit = true
