#!/usr/bin/env bash
#
# Configure JankyBorders.

# load variables
if "${HOME}/.local/bin/is-dark"; then
	source /etc/theme.dark.env
else
	source /etc/theme.light.env
fi

ac1="$BASE0E"
ac2="$BASE0B"
ic1="$BASE0D"
ic2="$BASE0B"

options=(
	style=round
	"active_color=gradient(top_right=0xff${ac1},bottom_left=0xff${ac2})"
	inactive_color=0x00000000
	"background_color=gradient(top_left=0xc0${ic1},bottom_right=0xc0${ic2})"
	width=10.0
	hidpi=off
	ax_focus=on
)

borders "${options[@]}"
