[default.extend-words]
ane = "ane"           # Apple Neural Engine
caf = "caf"           # sound file extension
edn = "edn"           # Extensible Data Notation
hsa = "hsa"           # health savings account
nd = "nd"             # North Dakota
shortcat = "shortcat" # macOS app
shotcut = "shotcut"   # video editor
spiritus = "spiritus" # Latin for spirit
