# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
---
properties:
  configurationVersion: 0.2.0
  resources:

    - id: Microsoft.Azure.FunctionsCoreTools
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure Functions Core Tools
      settings:
        id: Microsoft.Azure.FunctionsCoreTools
        source: winget

    - id: Microsoft.AzureCLI
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure CLI
      settings:
        id: Microsoft.AzureCLI
        source: winget

    - id: Microsoft.Bicep
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Bicep
      settings:
        id: Microsoft.Bicep
        source: winget

    - id: Microsoft.DotNet.SDK.6
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install .NET SDK 6
      settings:
        id: Microsoft.DotNet.SDK.6
        source: winget

    - id: Microsoft.DotNet.SDK.8
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install .NET SDK 8
      settings:
        id: Microsoft.DotNet.SDK.8
        source: winget

    - id: Microsoft.DotNet.SDK.9
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install .NET SDK 9
      settings:
        id: Microsoft.DotNet.SDK.9
        source: winget

    - id: Microsoft.NuGet
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install NuGet
      settings:
        id: Microsoft.NuGet
        source: winget
