# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
---
properties:
  configurationVersion: 0.2.0
  resources:

    - id: ajeetdsouza.zoxide
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install zoxide
      settings:
        id: ajeetdsouza.zoxide
        source: winget

    - id: BurntSushi.ripgrep.MSVC
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install ripgrep
      settings:
        id: BurntSushi.ripgrep.MSVC
        source: winget

    - id: Byron.dua-cli
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install dua
      settings:
        id: Byron.dua-cli
        source: winget

    - id: ca.duan.tre-command
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install tre
      settings:
        id: ca.duan.tre-command
        source: winget

    - id: Casey.Just
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Just
      settings:
        id: Casey.Just
        source: winget

    - id: Clement.bottom
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install bottom
      settings:
        id: Clement.bottom
        source: winget

    - id: dalance.procs
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install procs
      settings:
        id: dalance.procs
        source: winget

    - id: equalsraf.win32yank
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install win32yank
      settings:
        id: equalsraf.win32yank
        source: winget

    - id: eza-community.eza
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install eza
      settings:
        id: eza-community.eza
        source: winget

    - id: Fastfetch-cli.Fastfetch
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install fastfetch
      settings:
        id: Fastfetch-cli.Fastfetch
        source: winget

    - id: gerardog.gsudo
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install gsudo
      settings:
        id: gerardog.gsudo
        source: winget

    - id: Git.Git
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Git
      settings:
        id: Git.Git
        source: winget

    - id: GoLang.Go
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Go
      settings:
        id: GoLang.Go
        source: winget

    - id: gsass1.NTop
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install NTop
      settings:
        id: gsass1.NTop
        source: winget

    - id: Gyan.FFmpeg
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install FFmpeg
      settings:
        id: Gyan.FFmpeg
        source: winget

    - id: Helm.Helm
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Helm
      settings:
        id: Helm.Helm
        source: winget

    - id: hpjansson.Chafa
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Chafa
      settings:
        id: hpjansson.Chafa
        source: winget

    - id: ImageMagick.ImageMagick
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install ImageMagick
      settings:
        id: ImageMagick.ImageMagick
        source: winget

    - id: JesseDuffield.lazygit
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Lazygit
      settings:
        id: JesseDuffield.lazygit
        source: winget

    - id: jftuga.less
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install less
      settings:
        id: jftuga.less
        source: winget

    - id: jqlang.jq
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install jq
      settings:
        id: jqlang.jq
        source: winget

    - id: junegunn.fzf
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install fzf
      settings:
        id: junegunn.fzf
        source: winget

    - id: Kubernetes.kubectl
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install kubectl
      settings:
        id: Kubernetes.kubectl
        source: winget

    - id: Kubernetes.minikube
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install minikube
      settings:
        id: Kubernetes.minikube
        source: winget

    - id: Microsoft.Azure.FunctionsCoreTools
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure Functions Core Tools
      settings:
        id: Microsoft.Azure.FunctionsCoreTools
        source: winget

    - id: Microsoft.AzureCLI
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure CLI
      settings:
        id: Microsoft.AzureCLI
        source: winget

    - id: Microsoft.Bicep
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Bicep
      settings:
        id: Microsoft.Bicep
        source: winget

    - id: Microsoft.DotNet.SDK.6
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install .NET SDK 6
      settings:
        id: Microsoft.DotNet.SDK.6
        source: winget

    - id: Microsoft.DotNet.SDK.8
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install .NET SDK 8
      settings:
        id: Microsoft.DotNet.SDK.8
        source: winget

    - id: Microsoft.DotNet.SDK.9
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install .NET SDK 9
      settings:
        id: Microsoft.DotNet.SDK.9
        source: winget

    - id: Microsoft.NuGet
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install NuGet
      settings:
        id: Microsoft.NuGet
        source: winget

    - id: Microsoft.PowerShell
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerShell
      settings:
        id: Microsoft.PowerShell
        source: winget

    - id: Neovim.Neovim
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Neovim
      settings:
        id: Neovim.Neovim
        source: winget

    - id: OliverBetz.ExifTool
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install ExifTool
      settings:
        id: OliverBetz.ExifTool
        source: winget

    - id: PowerShellExecutionPolicy
      resource: ComputerManagementDsc/PowerShellExecutionPolicy
      directives:
        description: Configure PowerShell execution policy for the current user
      settings:
        ExecutionPolicy: Unrestricted
        ExecutionPolicyScope: CurrentUser

    - id: rsteube.Carapace
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install carapace
      settings:
        id: rsteube.Carapace
        source: winget

    - id: sharkdp.bat
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install bat
      settings:
        id: sharkdp.bat
        source: winget

    - id: sharkdp.fd
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install fd
      settings:
        id: sharkdp.fd
        source: winget

    - id: Starship.Starship
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Starship
      settings:
        id: Starship.Starship
        source: winget

    - id: svenstaro.miniserve
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install miniserve
      settings:
        id: svenstaro.miniserve
        source: winget

    - id: sxyazi.yazi
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Yazi
      settings:
        id: sxyazi.yazi
        source: winget

    - id: twpayne.chezmoi
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install chezmoi
      settings:
        id: twpayne.chezmoi
        source: winget

    - id: version-fox.vfox
      resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install vfox
      settings:
        id: version-fox.vfox
        source: winget
