_: {
  imports = [
    ./aliae.nix
    ./bat.nix
    ./choose.nix
    ./coreutils.nix
    ./direnv.nix
    ./dos2unix.nix
    ./expect.nix
    ./eza.nix
    ./fd.nix
    ./fzf.nix
    ./gum.nix
    ./hexyl.nix
    ./ijq.nix
    ./just.nix
    ./less.nix
    ./mcfly.nix
    ./mult.nix
    ./nu.nix
    ./parallel.nix
    ./pv.nix
    ./pwsh.nix
    ./rg.nix
    ./sd.nix
    ./sg.nix
    ./starship.nix
    ./trash.nix
    ./tre.nix
    ./vhs.nix
    ./vivid.nix
    ./watch.nix
    ./watchexec.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
