#!/usr/bin/env bash
#
# Configure bspwm.

# Start hotkey daemon immediately
sxhkd-wm bspwm &

# setup desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# overlap borders
bspc config border_width 2
bspc config window_gap 12

# focus follows mouse
bspc config focus_follows_pointer true || true
