---
general:
  startup_commands:
    - shell-exec zebar
  shutdown_commands:
    - shell-exec taskkill /IM zebar.exe /F
  config_reload_commands: []
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: true
    trigger: monitor_focus
gaps:
  scale_with_dpi: true
  inner_gap: 0px
  outer_gap:
    top: 40px
    right: 0px
    bottom: 0px
    left: 0px
window_effects:
  focused_window:
    border:
      enabled: true
      color: '#8dbcff'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: square
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: square
window_behavior:
  initial_state: tiling
  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: false
      shown_on_top: false
workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'
  - name: '10'
window_rules:
  - commands: [ignore]
    match:
      - window_process: {equals: zebar}
      - window_title: {regex: '[Pp]icture.in.[Pp]icture'}
        window_class: {regex: Chrome_WidgetWin_1|MozillaDialogClass}
      - window_process: {equals: PowerToys}
        window_class: {regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]'}
      - window_process: {equals: PowerToys}
        window_title: {regex: .*? - Peek}
      - window_process: {equals: Lively}
        window_class: {regex: HwndWrapper}
binding_modes: []
keybindings:
  # launch terminal
  - commands: [shell-exec wt]
    bindings: [alt+ctrl+enter]
  # focus window
  - commands: [focus --direction left]
    bindings: [alt+ctrl+h]
  - commands: [focus --direction down]
    bindings: [alt+ctrl+j]
  - commands: [focus --direction up]
    bindings: [alt+ctrl+k]
  - commands: [focus --direction right]
    bindings: [alt+ctrl+l]
  # move window
  - commands: [move --direction left]
    bindings: [alt+ctrl+shift+h]
  - commands: [move --direction down]
    bindings: [alt+ctrl+shift+j]
  - commands: [move --direction up]
    bindings: [alt+ctrl+shift+k]
  - commands: [move --direction right]
    bindings: [alt+ctrl+shift+l]
  # resize window
  - commands: [resize --width -2%]
    bindings: [alt+ctrl+left]
  - commands: [resize --height -2%]
    bindings: [alt+ctrl+down]
  - commands: [resize --height +2%]
    bindings: [alt+ctrl+up]
  - commands: [resize --width +2%]
    bindings: [alt+ctrl+right]
  # focus workspace
  - commands: [focus --workspace 1]
    bindings: [alt+ctrl+shift+oem_plus]
  - commands: [focus --workspace 2]
    bindings: [alt+ctrl+oem_open_brackets]
  - commands: [focus --workspace 3]
    bindings: [alt+ctrl+shift+oem_open_brackets]
  - commands: [focus --workspace 4]
    bindings: [alt+ctrl+shift+9]
  - commands: [focus --workspace 5]
    bindings: [alt+ctrl+shift+7]
  - commands: [focus --workspace 6]
    bindings: [alt+ctrl+oem_plus]
  - commands: [focus --workspace 7]
    bindings: [alt+ctrl+shift+0]
  - commands: [focus --workspace 8]
    bindings: [alt+ctrl+shift+oem_close_brackets]
  - commands: [focus --workspace 9]
    bindings: [alt+ctrl+oem_close_brackets]
  - commands: [focus --workspace 10]
    bindings: [alt+ctrl+shift+8]
  # move window to workspace
  - commands: [move --workspace 1, focus --workspace 1]
    bindings: [alt+ctrl+1]
  - commands: [move --workspace 2, focus --workspace 2]
    bindings: [alt+ctrl+2]
  - commands: [move --workspace 3, focus --workspace 3]
    bindings: [alt+ctrl+3]
  - commands: [move --workspace 4, focus --workspace 4]
    bindings: [alt+ctrl+4]
  - commands: [move --workspace 5, focus --workspace 5]
    bindings: [alt+ctrl+5]
  - commands: [move --workspace 6, focus --workspace 6]
    bindings: [alt+ctrl+6]
  - commands: [move --workspace 7, focus --workspace 7]
    bindings: [alt+ctrl+7]
  - commands: [move --workspace 8, focus --workspace 8]
    bindings: [alt+ctrl+8]
  - commands: [move --workspace 9, focus --workspace 9]
    bindings: [alt+ctrl+9]
  - commands: [move --workspace 10, focus --workspace 10]
    bindings: [alt+ctrl+0]
