---
general:
  startup_commands:
    - shell-exec zebar
  shutdown_commands:
    - shell-exec taskkill /IM zebar.exe /F
  config_reload_commands: []
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: true
    trigger: monitor_focus
gaps:
  scale_with_dpi: true
  inner_gap: 0px
  outer_gap:
    top: 40px
    right: 0px
    bottom: 0px
    left: 0px
window_effects:
  focused_window:
    border:
      enabled: true
      color: '#8dbcff'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: square
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: square
window_behavior:
  initial_state: tiling
  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: false
      shown_on_top: false
workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'
  - name: '10'
window_rules:
  - commands: [ignore]
    match:
      - window_process: {equals: zebar}
      - window_title: {regex: '[Pp]icture.in.[Pp]icture'}
        window_class: {regex: Chrome_WidgetWin_1|MozillaDialogClass}
      - window_process: {equals: PowerToys}
        window_class: {regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]'}
      - window_process: {equals: PowerToys}
        window_title: {regex: .*? - Peek}
      - window_process: {equals: Lively}
        window_class: {regex: HwndWrapper}
binding_modes: []
keybindings:
  - commands: [focus --direction left]
    bindings: [alt+h]
  - commands: [focus --direction down]
    bindings: [alt+j]
  - commands: [focus --direction up]
    bindings: [alt+k]
  - commands: [focus --direction right]
    bindings: [alt+l]
  - commands: [move --direction left]
    bindings: [alt+shift+h]
  - commands: [move --direction down]
    bindings: [alt+shift+j]
  - commands: [move --direction up]
    bindings: [alt+shift+k]
  - commands: [move --direction right]
    bindings: [alt+shift+l]
  - commands: [resize --width -2%]
    bindings: [alt+left]
  - commands: [resize --width +2%]
    bindings: [alt+right]
  - commands: [resize --height -2%]
    bindings: [alt+down]
  - commands: [resize --height +2%]
    bindings: [alt+up]
  # TODO: review
  - commands: [toggle-tiling-direction]
    bindings: [alt+v]
  - commands: [wm-cycle-focus]
    bindings: [alt+space]
  - commands: [toggle-floating --centered]
    bindings: [alt+shift+space]
  - commands: [toggle-tiling]
    bindings: [alt+t]
  - commands: [toggle-fullscreen]
    bindings: [alt+f]
  - commands: [toggle-minimized]
    bindings: [alt+m]
  - commands: [close]
    bindings: [alt+shift+q]
  - commands: [wm-exit]
    bindings: [alt+shift+e]
  - commands: [wm-reload-config]
    bindings: [alt+shift+r]
  - commands: [wm-redraw]
    bindings: [alt+shift+w]
  - commands: [shell-exec wt]
    bindings: [ctrl+alt+shift+enter]
  - commands: [focus --next-workspace]
    bindings: [alt+s]
  - commands: [focus --prev-workspace]
    bindings: [alt+a]
  - commands: [focus --recent-workspace]
    bindings: [alt+d]
  - commands: [focus --workspace 1]
    bindings: [alt+1]
  - commands: [focus --workspace 2]
    bindings: [alt+2]
  - commands: [focus --workspace 3]
    bindings: [alt+3]
  - commands: [focus --workspace 4]
    bindings: [alt+4]
  - commands: [focus --workspace 5]
    bindings: [alt+5]
  - commands: [focus --workspace 6]
    bindings: [alt+6]
  - commands: [focus --workspace 7]
    bindings: [alt+7]
  - commands: [focus --workspace 8]
    bindings: [alt+8]
  - commands: [focus --workspace 9]
    bindings: [alt+9]
  - commands: [focus --workspace 10]
    bindings: [alt+0]
  - commands: [move-workspace --direction left]
    bindings: [alt+shift+a]
  - commands: [move-workspace --direction right]
    bindings: [alt+shift+f]
  - commands: [move-workspace --direction up]
    bindings: [alt+shift+d]
  - commands: [move-workspace --direction down]
    bindings: [alt+shift+s]
  - commands: [move --workspace 1, focus --workspace 1]
    bindings: [alt+shift+1]
  - commands: [move --workspace 2, focus --workspace 2]
    bindings: [alt+shift+2]
  - commands: [move --workspace 3, focus --workspace 3]
    bindings: [alt+shift+3]
  - commands: [move --workspace 4, focus --workspace 4]
    bindings: [alt+shift+4]
  - commands: [move --workspace 5, focus --workspace 5]
    bindings: [alt+shift+5]
  - commands: [move --workspace 6, focus --workspace 6]
    bindings: [alt+shift+6]
  - commands: [move --workspace 7, focus --workspace 7]
    bindings: [alt+shift+7]
  - commands: [move --workspace 8, focus --workspace 8]
    bindings: [alt+shift+8]
  - commands: [move --workspace 9, focus --workspace 9]
    bindings: [alt+shift+9]
  - commands: [move --workspace 10, focus --workspace 10]
    bindings: [alt+shift+0]
