[colors]
ansi = [
	"#ffffff",
	"#d11500",
	"#008b0c",
	"#997b00",
	"#0057d1",
	"#a018ff",
	"#008c99",
	"#16181a",
]
background = "#ffffff"
brights = [
	"#acacac",
	"#d11500",
	"#008b0c",
	"#997b00",
	"#0057d1",
	"#a018ff",
	"#008c99",
	"#16181a",
]
cursor_bg = "#16181a"
cursor_border = "#16181a"
cursor_fg = "#ffffff"
foreground = "#16181a"
scrollbar_thumb = "#ffffff"
selection_bg = "#acacac"
selection_fg = "#16181a"
split = "#ffffff"

[colors.indexed]
16 = "#d17c00"
17 = "#d11500"

[metadata]
name = "Cyberdream Light"
