[colors]
ansi = [
	"#545d68",
	"#f47067",
	"#57ab5a",
	"#c69026",
	"#539bf5",
	"#b083f0",
	"#39c5cf",
	"#909dab",
]
background = "#22272e"
brights = [
	"#636e7b",
	"#ff938a",
	"#6bc46d",
	"#daaa3f",
	"#6cb6ff",
	"#dcbdfb",
	"#56d4dd",
	"#cdd9e5",
]
cursor_bg = "#adbac7"
cursor_border = "#adbac7"
cursor_fg = "#22272e"
foreground = "#adbac7"
selection_bg = "#2e4c77"
selection_fg = "#adbac7"

[metadata]
name = "GitHub Dark Dimmed"
