[colors]
ansi = [
	"#0e1116",
	"#a0111f",
	"#024c1a",
	"#3f2200",
	"#0349b4",
	"#622cbc",
	"#1b7c83",
	"#66707b",
]
background = "#ffffff"
brights = [
	"#4b535d",
	"#86061d",
	"#055d20",
	"#4e2c00",
	"#1168e3",
	"#844ae7",
	"#3192aa",
	"#88929d",
]
cursor_bg = "#0e1116"
cursor_border = "#0e1116"
cursor_fg = "#ffffff"
foreground = "#0e1116"
selection_bg = "#368cf9"
selection_fg = "#0e1116"

[metadata]
name = "GitHub Light High Contrast"
