[colors]
ansi = [
	"#000000",
	"#ff5f59",
	"#44bc44",
	"#d0bc00",
	"#2fafff",
	"#feacd0",
	"#00d3d0",
	"#ffffff",
]
background = "#000000"
brights = [
	"#1e1e1e",
	"#ff5f5f",
	"#44df44",
	"#efef00",
	"#338fff",
	"#ff66ff",
	"#00eff0",
	"#989898",
]
compose_cursor = "#fec43f"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#000000"
foreground = "#ffffff"
selection_bg = "#7030af"
selection_fg = "#ffffff"
split = "#79a8ff"

[colors.tab_bar]
background = "#313131"
inactive_tab_edge = "#545454"

[colors.tab_bar.active_tab]
bg_color = "#000000"
fg_color = "#c6daff"

[colors.tab_bar.inactive_tab]
bg_color = "#545454"
fg_color = "#ffffff"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#545454"
fg_color = "#c6daff"

[colors.tab_bar.new_tab_hover]
bg_color = "#000000"
fg_color = "#c6daff"
intensity = "Bold"

[colors.tab_bar.new_tab]
bg_color = "#313131"
fg_color = "#ffffff"

[metadata]
aliases = []
author = "miikanissi"
name = "Modus Vivendi"
