[colors]
ansi = [
	"#06080a",
	"#ee6d85",
	"#95c561",
	"#d7a65f",
	"#7199ee",
	"#a485dd",
	"#38a89d",
	"#a0a8cd",
]
background = "#11121d"
brights = [
	"#212234",
	"#ee6d85",
	"#95c561",
	"#d7a65f",
	"#7199ee",
	"#a485dd",
	"#38a89d",
	"#a0a8cd",
]
cursor_bg = "#a0a8cd"
cursor_border = "#a0a8cd"
cursor_fg = "#11121d"
foreground = "#a0a8cd"
selection_bg = "#11121d"
selection_fg = "#a0a8cd"

[metadata]
name = "Tokyo Dark"
